---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mikroskeem/ubuntu-devel
    tag: "ubuntu_18.04_vanilla"

inputs:
- name: musl_root

run:
  path: musl_root/ci/build.sh

caches:
- path: musl_root/sources
